apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5tz/7RnjJFr+2v6w25HTCkm36WfsCXd2VfLLaKBPzg==,iv:0W0Q/husx6iarITLYrBWa/SEEUTLpPuKChoQCzpLoAI=,tag:ClIPEEmgEtwkwrzmZyZfFw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ZwjkxKMZTo5d2go0I8XR7R+9v5u4o9VE5FEBtvVxH/qhmAOYVQ==,iv:ZqxU1VPlDlsX+rNdvSXIw5ywLVik0M3RFD75Fhsf7rg=,tag:mYPlJfivDIh3OpBSAl6LUg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:pTN8siUQCIL0cgfUM/2F,iv:pSkoH4a0SZMqpEBQbuOnhhoSR5palUoJnPqOCSuhMJ8=,tag:1gy6bb5iKRs6KeKAMDrrhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNmRiL2JXUHJ6ZVZGeTlP
            QTBpa0pQZGJQb0ozY05hN2lqR1dqZW16QVRvCmVFRGEvY2ltbThNMTRpVkREbEFz
            dVIrOFBzSVlJYlZCU3lvaHRzbGpYR00KLS0tIHRRTmFEblpjb2s4Tlc5ZlFLQlNh
            RFVmbk5BczdYeWl0YVIvZlp0TklNOFUKBA4t6qijXkLDYm5C78cEiF2QPbnqZr0r
            g0vSeK07lo6F0l00fSDuDgwNMt/Jl6oBF8aBTawUhPsFkh7VhOu52g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T23:05:45Z"
    mac: ENC[AES256_GCM,data:Jpf1PBLzb6FyGuuGCEFgnqYzrL7vQkWDehiZu8H/4utLC++a6wL91lsu6bdoYcdtuOWSBC4yX/ueWqPHd4BNfgIAF5h1sajUrWggKTsG8033FCEy+pC0Jn0MG6bafOUxBg1+v4qgdHWCZzpAIRArksUZIfIhMGtQRW2B8rxXkXQ=,iv:C/pTcJSGcvLMuTY8tubP689xPq9vvFdINv+CqxkwuwI=,tag:OIyUhL2lCna0bRzVBjJBhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
