---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: networking
data:
  config.yaml: |
    tunnel: 054ae824-08e6-42b6-ad80-83e873eb01bf
    credentials-file: /etc/cloudflared/tunnel-config.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    logDirectory: /var/log/cloudflared
    ingress:
      - service: http://ingress-nginx-controller.networking.svc.cluster.local.:80