---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: networking
  labels:
    helm.sh/chart: rlex-cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2023.3.1
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: cloudflare-tunnel-secrets
          restartPolicy: always
          terminationGracePeriodSeconds: 30
          ports:
            - name: metrics
              containerPort: 2000
              protocol: TCP
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/cloudflared/tunnel-config.json
              name: tunnel-secret-volume
              subPath: tunnel-config.json
            - mountPath: /etc/cloudflared/config.yaml
              name: cloudflared-config-volume
              subPath: config.yaml
      volumes:
        - name: tunnel-secret-volume
          secret:
            defaultMode: 420
            optional: false
            readonly: true
            secretName: cloudflare-tunnel-secrets
        - name: cloudflared-config-volume
          configMap:
            defaultMode: 420
            name: cloudflared
            readonly: true
            optional: false
