apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: networking
type: Opaque
stringData:
    tunnel-config.json: ENC[AES256_GCM,data:xmLPdQDWOBeSQye7wxggsY12gfnY26UtL+XJHeREbR29suZkWgstxC8UfOkbMJMFNw3gta6Fo1nWSSNXz2EyDFX8biqv+enoBQLnCBMbZhjWMg3A58HCd+GMedjw+oDyZosw+pjb8ruBnXnVFLcHvvBr+MDyRMRmPhhPso8FfHuU0DGxubGAuOiaQ1VW3Nr4jtg/UpOKogXNzJYI+jK3ikV117sQOBPWuz+CWLowkIEg5Cn0uBbCGAt0P3FG8Is9J9C6bAE97P3WUw==,iv:f2fGDptCJ8Ib+QOCOzpwq9hbpGWtWkYhdAhkKn63neM=,tag:A9Al3fc0GWwPd/S9Zp7/ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNnpzQS9LRHJTeDh5aEtq
            MUI4Qzh0dkoyeTBKUjlLbVJrdXVCK09CL3hBCm42MU1OUzFOaXQwSmlnL2VnRzVh
            Rk5ZSzZPcEF2dENLOE1PVTUxdjBRVVkKLS0tIDNOdUJHM1k0QjdLRG0zTHZadTdm
            OFdjR0ZZeFlrcWJRV3NKYjVPZHdTUlUKqzSdL9fEnhUYRKnPQWocRj6q4AODcSkc
            X4PBuHekcKtdXaL+XdtZ5HHagUvOiJkr19EVhIOQ7qIyFzQSGwlYqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T23:05:45Z"
    mac: ENC[AES256_GCM,data:msJ0zJ+GkBC8o3Brssa7Yjyv8yNyKmiRgrcgyVSyzzyd/Iw/JRZqLllurJZvYqqnDIhqfSM+YHqN1LljIbgpyK8XtHt2gRcEifoJwDkSzOj6+/ZDXIcdmkkkPS78ghIgZA9IAoLyvjJLJu+p17M9A0GNAJBXOdJqr6CkF3Zfuk8=,iv:aeg2sgLk5L/ETwzSulKeF207yF5eg0D1+nrKIPK1XAc=,tag:QoS4AWz2wRsm2W+nnMgWsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
