apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: networking
type: Opaque
stringData:
    AccountTag: ENC[AES256_GCM,data:ukBxRMKLeonzMoKRAe47W/uZp+Dnz+j1W/ljh3RSmVM=,iv:Rec/SWVz41nu9ocy+IyLHbHqtXboxH6e4XTDy4vHGZs=,tag:GA27shqWs608iUEA8JOXIg==,type:str]
    TunnelID: ENC[AES256_GCM,data:Eq7Y9HbU/aOn2EgX1CBwPpdVaH9xLF9jywukvXsls58=,iv:JGQK3oL6+3FEKI3uA14SArvf+OWo3sjpumo/GzWMJAY=,tag:eeKyIpuo2kFxnZdvNb1Jcw==,type:str]
    TunnelSecret: ENC[AES256_GCM,data:WylLxvsozo8lDaevTav/Iv+2cCquxYtd4OMTi2rwQTp8MFGtl6MyhaxjG0E=,iv:BhjXgXJ30c454YFA9SyR8W7y5hoZyJhbUHYB5amAvKY=,tag:2kwNvuj6eHtrr18rtMY8Ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dlFWaVZjdDFFcVpMdEcy
            U3NzTHphbFFpeFVudEJLYm9iaXBzSlZKVDA0Cjl2ZU12YXhrL0Z1Tm5XYjdObXh6
            YkZUTStHY0hlZnlXNml3L0JhcDlKdGcKLS0tIHZrNG9LbEV3TlNpTm1ZbFNsVU9s
            OGpjK2x0SlNUNFZpc1NmK1NpRlREQW8KJyvomjOTr+AauLcehVurm2Su+umM26tg
            VpW/woM7qamgTux58aiaDrHwzAV+7DIvIm2h6n5sILEYrTJKP5I5yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-23T04:47:27Z"
    mac: ENC[AES256_GCM,data:n5WX7NJImCXmYJswoZnjoX9J0Pa+9In39P4FDvPDZSUj2NVUlp56pWVKHgWda/xRv6PYnGIp86wIhtPIrJS9zhFdX2KZ4JQMk6CjGYmeYIlwIuM7/7HkLIZzn3CPXJDSvt1WO8YtEBkXKHu8VF4QlSd1rFSgycaHsB7DkCMkLvs=,iv:qQfX2BK8m7Fhyng6SR9QNqwfvquhN+o0k0iHmiopfCw=,tag:cpEvnOABNhPukOf/E52mpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
