apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: networking
type: Opaque
stringData:
    tunnel-config.json: ENC[AES256_GCM,data:KAi4VvyeLIpw1qA5mW5vh6pXesjgzeMVtxcj0+yLt6tOF08nQ/8m6VfYvnjHy3OneKD78GC5iAgIslJC1AdFxvWRQjO68P2Rsy0hAhpoLCHosWNkbpZZyR/F8kpI43x7VriA1A/EDHqRfs+esrjpGbFvuYH/FZ8dV+MBuCTEj38yx922zQttjxij2qR97vSZ3h43jQ+JtGsIANOCUO/AuWXG7YNPsTQ1BxcXhARhD6LlrBDmoGXl/rxrmGXr+Jk3ft0U2rBvNu4Tjw==,iv:s7MiYEu4+5vvbn5IeQoWTNLCtDodY406RwUCYyDB9WA=,tag:Vu62LmNf6oZF7ApRhHABBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dEZWOHJGcWpaTEgzaWlC
            cmNCc3hKZVhnU3prNUFnU2g5MkRyYVNNNXpZClN6QUtzTmhCb1NCSkpXeXhOd0py
            cE8vYXI1ajNQcElidWhMQVF1c0ZCQ3MKLS0tIFRzRVJwNUZSV2hCNEdMTzM2eERD
            aC94ZjZLcVpDeUZtNlZtd2R5V0YzMk0K7cJ60sMu5lu83+Airr89mksYyHwZV0Y0
            a15sKykuJz3nIzQecSzqk8SSKoLDmeS2ZM8XlN7KD0al858XPsts+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-03T04:06:15Z"
    mac: ENC[AES256_GCM,data:5w7y3PcKjuenZu6QDaUi3/K5gMgrNNo+il2ZR1LOH3ZGcHD6fR3AY4yXYmxve1vv6oOQL03fgAzX/udDhrgMcJBs6eNxNENezSt6PIyjI5a3pvAA1qO0QhaFJaDgobZrHVOctpRCwur8INObYnu3AC+bWrixojT6auTTGdjRmgg=,iv:qg5fHqWGGQh0Gcz7HySReRkeQkVsgRIMU8h69jFeiuE=,tag:j/DvcAfslfpNRky2CRZtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
