apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secrets
    namespace: networking
type: Opaque
stringData:
    tunnel-config.json: ENC[AES256_GCM,data:iItd2TnsmBVSF620HHfi2xH4aY9x6H7Qe7YHGb2qpFan+CKREeUWaF9QSwAAgsxqMLK2NZZUv9TFrmXgWKsEh7qlyn0I6AixHNuHLZLdvoW+Yav1qNi7bjJtVO0x9cRM6Hmxu3VbbUTgpi2p9C91iUoArs/YMA4vjYaCZWD9R+ckvuiR8hUfRJlD0sKghiJ6KaZTtiisF6f4B58Et+gU1umGTTMZ9SWinyz7PO/VSGNO1mq9VakE0paOkrKHSfFfPdPgFnoUOz4qeA==,iv:zAlIXICj2pcM7LtGs8DXHh4gEqt6ptongRHVZkA0PlM=,tag:FO4UympO5Eu7zPjxIRNZ8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaVM0MVNVV21GSXJOd29t
            OTZQMzdBM2ZuSVBNVTlOY1l3cGlXNVBKRVdBClJnU0RJdDE2VGlQZU9yZkhZR2Jx
            R0JsMy83d1pyZlFPZjRhOCtHTXBBUU0KLS0tIFU4MVNlY0lvZ0FUOEZIVVZUZDlU
            d3pwaVcvUm5IWGpKYUNneHB5VTVmZjAKkjQOt5FjW9FpcSPKzYpJrxLKsAg3FrwU
            xm0r03/xeUTJ3cXIeUkxRJNqBHDfkzUlhvpLOsfg687OgBZ8E/ullQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-07T17:45:48Z"
    mac: ENC[AES256_GCM,data:c+1Fm6Dzw56rVf15O1/WbPHUS9DHaGNsgpe6hYPItaUfe+D8VqZ88qmxcYD7cSOMfUqBh8bwb/CNTD2+oV1OYos6rWiZkdI7IIIivoqMm7YSsZBd4w3fCwn4uMg8xVNMls/kodxVT1dfS/KzvnVGg9PfO/yM94K005naJLMc0xQ=,iv:0omrFd5RZ5/LTZjGOZd2n+9HxWnzwXxqsOsZxT4igoI=,tag:sBiCuKJuv5TBRfw0qJfTMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
