kind: ENC[AES256_GCM,data:7aY2VslX,iv:GqqnXTtFG1BviGRy4OCX4Grhcmcu17mYQ89ai0Zxp0o=,tag:/oUuE/I1g1cGTeFG7weh5g==,type:str]
ansible_user: ENC[AES256_GCM,data:LRkpVKAl,iv:hj8izMWdNLfceBWljDPt38s5wLxci5NiXex/eEybHJ0=,tag:4ikfJjURSur97sjxBt0wyw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8GSfpVFGTH52DZA=,iv:cJu0fD335T6AKHcYvK0kxF9iq8Xp2ik3n2uuIw78PxU=,tag:B/F6CCZ6LRrE9CxNzCjg/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNU15VnJZMnhWd2UyZEVk
            M0k2R3laamN3QXNxT1MzdTR5NElDMTJnSTFJCmRuOFdCVDd3TEVMOGQrMnJQK2w4
            UThNN0YzcmdadWkrTmI2ZEVSQk9YSW8KLS0tIEliOU5zczVwRnR5Z0R4Wi9Qbmdi
            TkQxZW5wcjAxRW05ZWtERTEwSG9lbXcK1la/CP2DqHrkePZGx9ZFLjbl3cgN8EjB
            aJxHiLEPCrYk22mH6dTf0qtdyH7D8GsCwltlTrQnp4VOSIzRr2+3jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-03T04:06:15Z"
    mac: ENC[AES256_GCM,data:xi57YNpdMKio3rikQwXMNfKj+0rVo6X68TFlVY9lVxzdlVmAnVttvX2DzaxEoX8lqjxn6+dLVtEoXjILaWLEOhWBEWuagnOB3PYQOJCjwr7nmU3YlCyeEz2HszAUYu5S/cF9/V+P8IE4vuW4aDPOD4Ld3fTTMmkPC49Af/8snLM=,iv:9CD9mnkmB6TVMeEQyG+hNKpQYcPFkT4YJ682uh3aCvk=,tag:SBPt+NafQwxXjs6K4nJuxw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
