kind: ENC[AES256_GCM,data:2gvq8vS8,iv:6ClIyqDp0vbEbaRf/rVXeN2Wa1xnNIgLKhRn2+FUeSs=,tag:mgcY4QWeXSIaZymFSkBQ+Q==,type:str]
ansible_user: ENC[AES256_GCM,data:OnOsS4fd,iv:Sanv1ntcRJRurmcwIYvbqRWjtqBklh4e3RabeyMZ6bo=,tag:RnIpCy+K/BhlTbIJJ9c4Uw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Jw3KPO1CYa1QHtc=,iv:KUBLpf3GGwZcm+QbtsEFHo9oLseuWdcSpJ8j/pTxScM=,tag:eanOpf63gfUx92u1jyEMjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmejFEMUNqNHVPVkZaeUVI
            TWJLNnFTci9TOFoxM09ibDdoTTRUVXNFODJzCi81dTFqckd1Tk1RcGNIRlhKVG1F
            UU9ERTIwM09PN25OTzhlOGlLSE56Sm8KLS0tIERmbmhlTjd3OERuQzJpd3lOQ1Iv
            MzJoWHF6RlhFZDhHWFpVTkYyS0FlWEEKjqql9pTNz7vEPNvRq5hFvteENBZXuWWc
            m5eT4qBzS3Ux/9QZ/6Wuxd0Kb62Id8807RJ9jAe5R5+Ar+5e3N3TAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T23:05:45Z"
    mac: ENC[AES256_GCM,data:d9MObN9PQlQzY/WDqYTdTzXj+gLfojxjvKXRycjX93Wl+BoqVmC2h9XM/DrarVnxePVR22/ge/8NLuh1MMh/2mMl1HO2Em8PtOVRrBoAcWSLrqpJLucqCQNx9hxBuoFt/3z7eeXQaBFfu3M5HsOPz9Bp/KyUfFH+kX+oUvGvHb0=,iv:tKAIqd3wgOHduRZbi+beJBBh6mcWCIrinnPE9jZorOU=,tag:qa3IZ6cr8Zq8AVCulIs/Rg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
