---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: zekker6-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://zekker6.github.io/helm-charts/
  timeout: 2m
