apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9F0LeQyHjjyhzSsl0RGgRigTedC7/7IxRPLCCoQU7c5EKJZZUidQDQ==,iv:/kknu3MSwd/P+WfNtFpXcvf1ZP2FwPyDHo8RAjXqQ4g=,tag:lbUs2bdR87gRoKa41/AkLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNWJNZGIwZDdud2ovMWRG
            SFM1R3c4QmZKNm1aaVY5NFNZemRjaUVITkhVClM4MDhGY0VLdnBvZk5jM3l1dTgy
            U0FuVVFYcTI2akNvbmxONnkwV1hkMWcKLS0tIGp2dlNWSE40azJ1L0IwaC9lNU5G
            Nm9RUWdvZzNRYjE2NmZrU0plcTdKS3cKAnvUJ+25wShni+0OEINe8sfgyESQ6FBL
            71YeSltZNSRXBfiROGO/GTCNi4RBRxW1ncyd6WlNq6p6PxyyeQDr4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T23:05:45Z"
    mac: ENC[AES256_GCM,data:FvwuDaxn9zwr49Mwu7Q3ov5JuWWOAUJOG7E37T4PwZtwEoSSNR7hcI+TqmzhBRCUbETm37cllvBZaG4wd3iL7cZgPGjR4o73/qvamTPmOPIoeBUX2eS5MDM0FVwdvdX8g1+W3hH1aqAZzrT/IkvcDrjG+0aHhvFmjWMdtteCukw=,iv:N2Y+5T21fQHRVHlUT2Ic0VYGJWghzk5dyA7Qu6K/zv4=,tag:r0XmzZ0pX8l1YZl7NlwKzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
