apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-backups-secrets
    namespace: longhorn-system
stringData:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:yd30FN2M62zUE8hDifnKPyfVa7p/fP09rEuxjZvqj4Og0XAMNcaUcHDCsIYbPSoOmh0L8dvviA==,iv:dMr/RnEfS6rujwOkZzAuyBMwQdb88Y0T6VkoMt4pXLA=,tag:viuqwBIDJZ1CRfuLf9CCTA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vg1popvD12/mhlE8P66v5XVzKKM=,iv:SnBeEYdirjzWgb7YLtkm0QmMsaRyMIYz6R4mKliUbq8=,tag:3XotDB/c1toe9VuEP+E8Jw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tKM7bM2PDslSvvV9j2W9qQGl7DwPpfdJamTzIfxa8xzs+QtOfhqrsA==,iv:PCNu6LfJyXszpE4AnKBo0WLTydvhkx5bh7UjdcA3Gro=,tag:mj73rPiVqJR+FGjt9rlP3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUkpsK0o1LzRZMmFOcGc4
            S2NiZHEyc0d5TjczQmxEK2RpQ0VBOUtqYkJnClZqNnZxcVlmR1BRSzQrUC9ST0xm
            VGdTVTFrNTlnRXBiemViTlNpZDU1Y3MKLS0tIEova3hhc09DZE51Q2hMcG0rYUNB
            R0szdFkzY0xEV3IwVDBtV3FsZVE2ZlkKNxd5HnJyxGWhiYzP/t5QAFOj46x0jOx9
            xGMFfBNEY0MdWh0CiwVSJUXTu7Y81juurCMB1jwABi7DFDrRQgHfOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-07T02:09:41Z"
    mac: ENC[AES256_GCM,data:FI+SUJTuYva99ywzKpkw9q982CGvXMCm7GM4p8MWUijlI7W6m4lU5Wby+6lFbDZIe+toD21/tgG5EhUdvEHCJaxF9b2a901B3VAmZ//kw1/8gChl1S7W2qPcssybWYZw7rvKhMQKIpYSEylNn1FAqLMmj054reb5/sFsprc8EDs=,iv:X8l+MrB1C6wacnNmc82+FKju2quMDFLDfJ9ld67/LRc=,tag:a/Dfzp+nwrlazcFYNWrE3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
