apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: web
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q8UZTmu/7sRP9IIZoD8rwlBRWFUB/YUJCprB,iv:wQFTJmdS9hTFFb7fvjLaxtm+15ccHjkXMdefJA3C9oI=,tag:CC8tDnOx6kPkTrgGzdO5Jg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BbC2oSWjwWVP13YM0fG5FjJJYsHswRwmq39DF3V/fNffQgVWAx5xutCJ21Qa1VI+LIg=,iv:Sfc80T1ZW0Hv/7qTfpfUYJ120MtiQkAKhHG5hcCQubM=,tag:952TSLh7KSGyehdzk82cUw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:p7VWtlArwQgM44w2llfAWgAYhhfAwaqR+uUMXgiwa8n22HIr/qwA/bosFZZPCkxMfoA=,iv:yXCTnGiVCvZAxFUHrZIgETE9QfZyUoMYSfyfhvsU6cA=,tag:JybbmqKd8Nb3oWKafcS2qQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Bzg1OcvtsqZ+dbOYktHkeAtahHr54ViEwyPgw+tk9Vv+heLKUZc0HIc3XKk9WAj4hvI=,iv:elIC93QsgYUp7HnABGQWIDjDkCDjP52GLS8s8IWtYPQ=,tag:Tretfe0qu2lXRaT4FBQ4BA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:xHgNL2M5UTYaJEXpkmvksMWWDNHDPyjYqzepPocsgk2AhDYWTM2ZH81X+X00hFtA/vY=,iv:XSDE9QOhdS19zJAsZxLFcak7sFCWTXp6mtaKZgcRBuE=,tag:RprnV7iqnJfQvwllnWfsvQ==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:LLeWHg+H1pZDFDhwFYm7DS6h,iv:KbjTpCeR7UGlhyqgOai/F1HR/ZfIxWFe2l5E1zb1TjA=,tag:0Rab4DzFq6b05uugU+SsqQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:bgWdIcJhVERSgyiusvLFkFiu,iv:hzINVmPXvdryJoAs8RSPLsSlb8lt/Xp5gM8aDXivy3o=,tag:dF5A0L4POGQu0ViZ+F3TXw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:1Csc1/Q=,iv:CYWOC2ceogUYdWr1TQpVDSi6Y8JThzblik3ocFU1Hz0=,tag:OvzDJkuQnmLFi+rQfYxx4g==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:AwrlJLSO7gk=,iv:1+fb2U3QPwiBqdD7xYjUzd5NoqiRsSGUXmDlcSH90D4=,tag:zMI+OqHQHoL41Bad/zm8cg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:qvb5DItJako=,iv:iOeya8bQSiaaAU58cSuET7X/UQugn4B+VSJLrrYf91g=,tag:ZVd6+aPQVvRWlB9iHzq+Cg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:PoHxtAFM5RQQAnyHN4brJObJGfDHnH3CaXGp0h/HOcBxIUNuhdshCd2LmtNj9ogotB8=,iv:VhszAvkR9r6kiTTFtKuYUI95LGtXloZxHRcsKCraW+E=,tag:FN33lM4aeJr/zDEPtl+3EA==,type:str]
    URL: ENC[AES256_GCM,data:rymyzMYhgGGIlZlnhxiUs2nARD1chU0RscY=,iv:Aqo2e+VUUcO2hMJA2hYXupsIHbY5hw5hIc/VWMjt3Zo=,tag:XsBQ+2/8cqmDpsugQH0ocw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:lBRblfNKGaAYGN/ZaZ/m6F7vcgnuywbhRDlufANi+RauIEjZsGZBgmBdFGKgJTipdhP49SoDRR0o9iP/tA/jcN+y1STWtRHON1TIJ4IfuzHUe4oQ9lw+rJyY84Q=,iv:WoBPAi1AMd+iEyN0OAot/yxR6eLIRgRQ61MhcKdYrZ8=,tag:FqWO1lxD9ktvW8H2g9NTBw==,type:str]
    DATABASE_URL_TEST: ENC[AES256_GCM,data:4pXbn7P4qPfiHgZjr9O0vi16DoBiI+WE6EI8pbZkWd6ixjWBWO+XlLxW+3YbCIjCosbbBvb8ZNtaAR88b5/F/KzOmEUcPkxWWjGe6cQHVVil4fZyuPjGeE+eG0flToJ01Q==,iv:8VGn6rHjS43/XX4O732kpOcc2cK1KhcV6WnpCrPNfvY=,tag:IXfJOMwQTG87AjxWtE/fzA==,type:str]
    OIDC_CLIENT_ID: ""
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:fpjhzN7rQ/yzs86eJypP3DcdSLJ2FER+hG/4hljMoAFKgSwNJgOE19QMcWYGZuCLCLHhRdA3ocRe4v3pOgmlqO7LvzSP+H62Idz6Bf/o+hl/E2MguwaTaQAQIVro4TCWjawNxrKldIJ58UTUIf253pyV1SPvO7UES+Gb1mG91Es=,iv:qs75HapTZWni1zpTRyWjEjFWQn2lAbexFetcn0mRaDY=,tag:6CGQX+MJbHh5adDSDDgDOA==,type:str]
    OIDC_AUTH_URI: ENC[AES256_GCM,data:1DmwrrzSEHKEsPMGik/aqnXgnAE8OFvJQH6OEeVdb5XTMXPAOHnqN4ZRWVHk,iv:TuRJtJ8lz1MBU4WgkMurrsdn32x/g8V2IzJR/LPMCNM=,tag:81rmTQ5NlKCmsAhocv8abg==,type:str]
    OIDC_TOKEN_URI: ENC[AES256_GCM,data:BEwJ2g1eJCJqrw8Cr029eVFKpTY8BT4guyGVz7vtK0XtRs9YqpsK49Y=,iv:+peMWlj6iJV5vEi7jhaWXkXHAZwgunPCYWlN/TwwXPU=,tag:YluSPBkJPU4vx5Qn7jQmBw==,type:str]
    OIDC_USERINFO_URI: ENC[AES256_GCM,data:R9FBK6jhwz05IQNWvVzlZse52FErSlIpYReFIRj9SfJozLbygM81MAck55Y=,iv:JNQiwWACM+UNgBtGFEz+gYVIlFaz+gk+2qtzi2q6PQ4=,tag:j9sO2w4VD7JydR1pwlGAiQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qYg6v02b6qFGyL5lXL7qeA49Q0fyj4mEJfkGdWqU7wzFlCSifbAEvpsylC1uaAJPRx4=,iv:uB7qJsrTeCRMIvLpMfSdx4FpvVH4BHxCJvRGRuV8YXA=,tag:hzVMyEPFIPBPH+QoqHcm0A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:PW6MSASRuw==,iv:D0rHbZsVqyD0TWx3LXLdvl9h8aIrH71ie4lQBlQAHHM=,tag:UjAw7vbUKYsvFk6j+QaDpA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:QamUmeP+UA==,iv:KIpu8Zfx0eFBMQksU7H9+srzDOLz1bGUFJ7uH/CQzgY=,tag:Yxnl7Sf3zxi7c6kMJe4b0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZmJ4L3dIRGh0cXNQdWdi
            ZHRMYUxoZTJHeTNwVmFxcm0vZXF0bmdEWlhjCndvb3BWcTA1SmRuVUloaU5aQWJC
            Z2lzelVHbkRubDEvUHY0VDJQZWU4OUUKLS0tIFJ3MXRQT2xoVURjSHBiRHZWb1kr
            M0w5UnNXMnpBSEYxOEpDT2F6WE1VSHMKIjvWu9uzZiJ2W2NXTTPtKbB6JHggsQYz
            x5ki/aBjCdpUqMz6gXL1b7FpUZ4R/hsAc+V6CeH5jtm0kbTRtU/HaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T22:14:46Z"
    mac: ENC[AES256_GCM,data:2lUyG0lS5+hPnB6v+d+kq7aBc45hJlmhp6SFcr+MViPpnSEe8gip3FfdVEUmZjJ/aM9FHZ0ls/LefQQPaDG//RsCOFr9RhM7fYljgdDTj699JEWNSUrCwi7VIGdW6jik3dMkPl4m79s7IpCOU0wln+sIEsdKFG57d9yFDGy4S7w=,iv:c8Oq6+Cypr6NdvEy/90PfEPUKlmKAu/v4Tqq0BOuVLY=,tag:Wm3dPW5nfEudl6Zavt0meg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
