apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: web
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TstTpelYhZ49cTRTGm27gA==,iv:uLoxTEu7GKKJPLQ9uPQ7CtwXgkUgl1hNgxQLFUU7ykY=,tag:Uw9Fp8ZO1ZftIMxyMuA2hg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VK5MjsRVsxtQ2bv/Asx9kyrMirsrvoD//wOtv8YXV6o=,iv:HtEeilGIqhy3LTmt2Wx4FUiZ1G5qmTJixR0Y/G4diGU=,tag:k8GFHertxVnrQPJoK9CZbQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:knNrXVGUhyDQxabtaBNkcNDykxvBU3mRTiuAfK+bmU35PISH0v4IfaDB1rLNDFRSBuQ=,iv:m8vfNWy8UeCaM5EcQxoSrPVbqNYhO0k1O62y/7p1fJY=,tag:AkziLqRKqnlIcXvBNwXmtQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:I6KhOvyoeFg+r248aJHoJ9LyrefU9cWQKSqQpHfynJnmJp7ye8y7az5pFB1kx1+vzV8=,iv:S+s9RrYCqUKOr2Y8uZ8BXkBLmV7Bguq/2fTxJQ/RBUQ=,tag:6VRJtsgIEfxazDDsaByjzQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:7R3V9gsaHr3iiiX1VJ1gaaU7+sUgWB1Pfc/n4WmaP8/boX3y8kuyZvJK6h5wGlvMOWDv///c794flJhh1SVBVQ==,iv:H2qcnNF0HehDwHuNDjUcpwSpG5buWFseXm6sWdRdTg4=,tag:jx9CPPryfnXuXWbJqP1XpQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:X7IM42bskEXHRPVGX/ywFAFHx5tOnwa0ln1zl7sV3c/k9vTrXqxP4ECW1hNFVPPnw49EnG9mVTZ3XH6KrzPv3Q==,iv:kcFIx+Cu/0RRvqhU0hGk1HSsc3XUgv6BTpoRHx0JxAY=,tag:rmusB5eP+hpsVxjN2eaLPQ==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:hcu0Zy7aF+jWDuwhj/Ytks23,iv:9qjImpYOD0a6UAbUCmz2iQEbM2AtEuqQPmPZ3+RqzBs=,tag:epQc96zWiIjxmH8DroM+Tw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:HkgGqo3T3FqVmx+j9yQXVitX,iv:CbzPwRKRSIFr8oBHbiiDLZwL3iWBzYxFTdLg8LTUoHQ=,tag:+EmZrzX3LablOG5PfzqYxw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:W0DM+dM=,iv:4J4bzCyPtPLnqvxn9HAMKmiOD0Iz+5MT5u4rT/r0N4c=,tag:inoWtOY4ys+CDFymJ89dmA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:CLtsLl+rKN8=,iv:CasnHYHEVZqDKLML1k6Zwj44pqLnfulJoQu74b5rMbw=,tag:AGyhbDPIcPq4FH+mWudEBg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:5/3EkR3/RfQ=,iv:3EuDGkaEO7olvkZ/M/9skTLyKPiK3NX6O7U97a9z7u0=,tag:2CmMK+Fv9sCNa+m0hhajCA==,type:str]
    URL: ENC[AES256_GCM,data:8aO2Kpk+rOtHf9XnbuutT/cNJ6LuCwxxmcA=,iv:o0Ju5wpHKrMyPL8Viucvxaqg0LrAm0iy9p9A3C42t9c=,tag:sNKmNLf97BVKyGWQW2PcNg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:hv3Ll+AMNaK8l834jFeogj9kmbVFMoI+/ko8SCuJLIlqRTyP3A9YmOBw7uqTWBH0jvD5Rk3w6OCE6NxYATgaV35cIHsI45BQBjT5grnVyxbdimLfbloBkDiPFVE=,iv:HCamnFDy7SIrscHYRqCg8oQAdutA3a98Xotma9G1jbk=,tag:znOapG7S+BujAY7D1nLIJg==,type:str]
    DATABASE_URL_TEST: ENC[AES256_GCM,data:oRRvChewDjjo+hWP3ljuaW/+n96iXfciRx9omy653KG04bMaQYfgYa6LR83mFzR/UpEnS3w8dhdIsJ/E7WvE5o2WfCBKb3XAQIsnjbmcS0i5rodmWIqQyuUbOu9r3c4WIA==,iv:vcbg8i5QJtY6pWr5rhWpuv1Wyio6dzesvNOLkLnJ1lg=,tag:Fmb8Qm9JudPagTdf+C9uXg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ppdgM/x49sc1OeLdUh/gGp0/iQfK9gUYjbRnXFZG7opuQntwQxea8lIb5xxzIEdNehA=,iv:+8A/hiH8ISwROjJyjCGNJ8CQQ4xrX8PxN82QWaDUu7s=,tag:X/eydr5AVhXaG00Q/xxHxw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:e12apEywsg==,iv:Df+kofzHK5fVk6HOQyr2cmdrNdFH11pJTbDDJBfEKyg=,tag:3719Mp2nsYIvNR+n/4rMbw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ACdFl4/D1w==,iv:VvCbmb7oDPjk5F0AbLopcanhuCNEGDS3oZZoEeGRBXU=,tag:BV6tf5JvSFyYXRq1yfIqYQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:3epY/HBMyDqMGZNoh0o85MoYeWRH7lYdCAsyampkSaH/FCDqADr/bg==,iv:asNEv9GP9QAsrdQ/rV5AgJ1yVqOv72SP0427Qn/u5mY=,tag:lZ4/plwQjNp6KJ2oMC1MHw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:dtjFYB7X05J7Q7QFZUqPjRoWC78JhwK/Okw4vRc7ER8f57pD7taPDteNRFBDlJcfcbrYO81CFELaBUgH1qlu29t49LZpBbIeVOvyHuhb4FQ2ZBQyGDlf6BCyCy3Q8xqUvl0U3hxUcL8hLqTUroc7b5guH3z5ZyIZSStlHngqCEM=,iv:5njymWjbMsP+sse6mWTWzg8xc4j3OLqkw8iV0CUJHYU=,tag:xDU9Pq8ODdiNuVepS7NGsA==,type:str]
    OIDC_AUTH_URI: ENC[AES256_GCM,data:cN/LUIvj+SvBbek4kp+Js9E7UaS1Ad2+aUGWtS9YonV6EhAipl977teyRuhx,iv:XWkqDCuJ6GXC21K7zkRG8F0pQSgWaP6H+vbQBurD78g=,tag:17FHujRyNpeKU+05ifjJmw==,type:str]
    OIDC_TOKEN_URI: ENC[AES256_GCM,data:quk4s289Fcg8cmuFfY/WvVNa245NTS+5wyQwIUOhcTizx1db1JtrXJo=,iv:caUALMAaH+/eJtCsZmHg+NmVgUaLsC2bnpRp791soEM=,tag:JrYP36QaDIyUVQ6/Hz8DQw==,type:str]
    OIDC_USERINFO_URI: ENC[AES256_GCM,data:FmDW2eFCDdfAiit2Z4kGXo2ubi2Yxh8FhUBqz3BJXXDWyBx4kceCcRhPHOM=,iv:N0DNJt3QQcSOd48IxZwxdC7vXet17J6dgnhNvaTMt+k=,tag:kc35YEU39J/yUp/nIfgSvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRGNsVkx2SzB2ejFJUnRx
            YzlrUHR4WHd2MlNzQmoyVXo2ZHQ0UkZlWVE4ClFVdHlURFZrSVZ3WjJCTnU3ZVRl
            WGY2QlJNR3M2Z3NnMkw4L2hheWJZT1kKLS0tIDh0VktpYXdPRkU3RXd0UERzRHdx
            OHV2bnZOVFBBc0dhMFU2dllTRWFVTTgKqidUN5WfnLY/zWB4Gf/NOpz8ilHujPNx
            witP8PagsGCzCnpNdrx7W0Vlt7oHGR4XJS11Dbf5Wp3mErmj3/7gAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-16T01:52:59Z"
    mac: ENC[AES256_GCM,data:GiYWxdXL8kMhvldY5hwJtfbCPD4e4JZ9I548gPsUK6Kcjo/4hmvRe0mZaQX4nwAwtDhBdaVLh0FE8npkrpo+GPvFMH3kaSFHw/AFHE0vM5etjigUNPHTuzA8eIKLCuWS+UNzIWn7/evH1g9kL4Kmx7z5SOqY4O0DDLObwWn+0zU=,iv:zhcjqa/pQ5h+GUV3a3Z5eIsQn11As11lUbZHzO64LjE=,tag:vxhGexzPYK71MjrpQTxcKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
