apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: web
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: websocket
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: minio-s3
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: minio-console
  selector:
    app: outline