---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-networking-cloudflare-tunnel
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflare-tunnel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: deployment.toolkit.fluxcd.io/v2beta1
      kind: Deployment
      name: cloudflared
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 5m
