---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: argo-tunnel
  namespace: networking
spec:
  image: cloudflare/cloudflared
  interval: 1h
  provider: generic

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: argo-tunnel
  namespace: networking
spec:
  imageRepositoryRef:
    name: argo-tunnel
    namespace: networking
  policy:
   numerical:
      order: asc