apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden
  namespace: web
  labels:
    app.kubernetes.io/component: vaultwarden
data:
  DOMAIN: "https://vault.${SECRET_DOMAIN}"
  SMTP_HOST: "${SECRET_EMAIL_SERVER}"
  SMTP_SECURITY: "${SECRET_EMAIL_SECURITY}"
  SMTP_PORT: "${SECRET_EMAIL_PORT}"
  SMTP_AUTH_MECHANISM: "Login"
  SMTP_FROM: "vaultwarden@${SECRET_DOMAIN}"
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_ADDRESS: "0.0.0.0"
  WEBSOCKET_PORT: 3012
  DATA_FOLDER: "/data"
  ROCKET_PORT: 80
  ROCKET_WORKERS: 10
  SHOW_PASSWORD_HINT: True
  SIGNUPS_ALLOWED: True
  INVITATIONS_ALLOWED: False
  SIGNUPS_DOMAINS_WHITELIST: ['lab17.us']
  SIGNUPS_VERIFY: False
  WEB_VAULT_ENABLED: True
