---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: web
  annotations:
    external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  ingressClassName: "nginx"
  rules:
    - host: "vault.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: vaultwarden
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
          - path: /notifications/hub/negotiate
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  name: http
          - backend:
              service:
                name: vaultwarden
                port:
                  name: websocket
            path: /notifications/hub
            pathType: ImplementationSpecific