---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-config
  namespace: networking
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250M

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-data
  namespace: networking
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
