---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trilium-notes
  namespace: web
spec:
  interval: 10m0s
  chart:
    spec:
      chart: trilium-notes
      version: 8.0.13
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    image:
      repository: tccr.io/truecharts/trilium-notes
      pullPolicy: IfNotPresent
      tag: v0.60.4
    service:
      main:
        ports:
          http:
            port: 8080

      securityContext:
        runAsNonRoot: false

      podSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: &host "notes.${SECRET_DOMAIN}"
            paths:
              - path: /
    persistence:
      config:
        enabled: true
        mountPath: /home/node
        existingClaim: triliumnotes-data

    portal:
      enabled: true