---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triliumnotes-data
  namespace: web
  labels:
    recurring-job-group.longhorn.io/critical=enabled
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G