apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:obAWMYZ4q1XAme3Vy2TJbhivtj3fN6vjc0AFQsx8Mg==,iv:nFbJgnC9/ETe4ZUzWy3gP3VItnWTpnU5hvCjQ+qq50I=,tag:nVlfdCt3XPKUO69vOsIiAA==,type:str]
    api-key: ENC[AES256_GCM,data:qQppI6YQxIOzN7myS2wmk7FiJgQhW9+GIX+A9AZASmbiBwykSw==,iv:jyrQJOuVb9+oT60QtTkKrTNpcdHnvgUzs1H3s68HXoM=,tag:9m3+9gfXD4svgO93hROqbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR2RyV29XWGJidlZxZjFp
            UUZxaUovMHl5bHY0c2pTbzlKam9HUHhyb3hFCm4yNFJqdFg5OWhwdG1GUkJQcTVU
            cWdHNTBnMUJ3Y1B0dE5nd0lpVzAwU2cKLS0tIE5lMUlXRlEyT0xnYllrQitSMDJj
            cDMzdm9wWGloeGQxWHZpODg4ZlVaR0UKMrGJPdIxEPg2uDUlYiIZsZm377u55oKN
            Qui+VouRZ4sjbkygLVl8XWpM+0wJfbQ8HdsJQUaSPhmPnwc/A7qqwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-03T03:45:07Z"
    mac: ENC[AES256_GCM,data:9yVjYNlW/A0CJH3DYn1r0ZJXFYyCBhEKgmKoJ4D99XXRL9u8H0sZcctnHB+e0Hnnx2mJTloGik1OrkYCu4FDZxOV365OcJDKhRVL+HqPze2wqyZCkibaLcR5oYZziQLhi4O5bGWRhx8Z/6BJQO6qGvHx/e1j3ToWlTeJ5DB2/zc=,iv:YkoV94yUZ2gq9z2F3Cmi/CfgTulFVyuSRtaqSv0yxXA=,tag:7GBnJM/JDDjSOKRYbDCE/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
