apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:nbcPpSPe4isigFRF8yESeT94D24J/5yJ1AE1Wax83g==,iv:0zkGoy8wPDbxyW9XFztEKoT2Gr5CjUF4+N35cGQ3014=,tag:04IIYbm9p/T9zEFdYfHMjQ==,type:str]
    api-key: ENC[AES256_GCM,data:jrGrrPtptmo2Q4sbfGKkbs4xtwtGf/EfLLR1mUNvZepaW7Jq5w==,iv:mDL8yhxhsXLNtaoM2C2H9zV02k4eHJlY/Y5liH+ZIgE=,tag:P0uqzuY3wZvxZ9XRvoqeHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2czWVEyczI5M1F4Rmpo
            Z3h3UDJjd3BXMndsNnhlaGMxOTBLc0Irc2lVCjd5bGJPWnA2a2RlYzdqMklFUWRT
            TWg1ZGVocTBmRnNWay9oeWhIdGprazAKLS0tIFd5eC9TZXN4WmxoVGV4MzJlRXFy
            a0xTR3FTUkw3UmlYZmg0TnRRUXNtZFUKXzpQFNcTk6JrbqToDpWznLZeEmOqWMLR
            SYuBbQmaxaqYDqP2+xbepM8518NMdMctUua+aKte/UvJ4x4hRR/S2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-15T05:25:39Z"
    mac: ENC[AES256_GCM,data:RyyMDadN2ia66d6g4Bdh3md7Oq/017f76juMM+8r4DJkiOMqwThd9OZ0sdTnRcurMNnfmNa1Ib9yKirz8R02JTBYHkHabBY1KFDJETDuueW39R6OyEoCh6Ly7OAo+aE3/8Ewo/GFmwTNCn7pdkiQEJ4X3lSty3XiNNwoB737GJk=,iv:SCAUIMBeYa0G7Qkg5vp1+w4JeSEki39rXZRS9jyh2pw=,tag:kLgg3IEYVWp01SMaCWVezw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
