---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: web
spec:
  interval: 10m0s
  chart:
    spec:
      chart: vaultwarden
      version: 0.6.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: gabe565-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dani-garcia/vaultwarden
      pullPolicy: IfNotPresent
      tag: 1.28.1-alpine
    env:
      TZ: America/Los_Angeles
      ADMIN_TOKEN: "${SECRET_VAULTWARDEN_ADMIN_TOKEN}"
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            port: 3012
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "Request-Id: $req_id";
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
          nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/limit-connections: "250"
          nginx.ingress.kubernetes.io/limit-rps: "300"
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/upstream-hash-by: $x_forward_for
        hosts:
          - host: &host "vault.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012
    persistence:
      data:
        enabled: true
        retain: true
        existingClaim: vaultwarden-data
        mountPath: /data