apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:s72mW21VHnt/JQ==,iv:t1dHiSSWvLJ7DGeZO1rNYhoZFYMVihr+CQ0mFpxr9L8=,tag:E9Giifr5U4W1oH5Tye1Q0A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ciAorNZQ1PX1EXuDi70xPGZK/NTq6fSOqQRQtmq2Jg==,iv:TLCIVLUrtVLU+MfQO5vqImWG3O/K+Lchsu05kjOMBqo=,tag:qWp8sL/QZHIFJktZJ8DwTQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IbmSGpEDg2lL8UMe2yVHJjzk7OHs7sCqXKtN81xHWLII+SJB,iv:owAPFTCZNOAR4REiU/7yoyX439GXxtsVTKoRj9/oqJ8=,tag:yPlmj3/DW/Fx5MsM/7t/1A==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:giz+lDUaWg0Mwn3wTE4uLpwJl9Zv+Vg67h51fz7u/sIgJT0WaGFE/pee5LdSrIVnUW26f5zkbxVZTQOR70llrZXl2fxovfbS36PxhzB5G9pZ7mCsi7o+XcJGooUBkJH7G7wKtWF2a4equW5CEINeRguwdKkPBlrwBusS4uuT/EVwgSBVf/tJs82id97yyrJwon1wk98RzJUj6s1xaNQM,iv:/G7DwE8B/4Iq3QMXcigMI3ko2kKQhhBN9ljR5U+GPQg=,tag:/ujAobL+NipO0v+MHSnjqw==,type:str]
    SECRET_VAULTWARDEN_DB_PASS: ENC[AES256_GCM,data:UUFW/GLc/U+DMycpvUqmgt2nxHirRN4hLyntPaDnKGY1mQ1gqh7Q,iv:dyOjEbDJxSk44H9cHDeAqHqc/EXeTxpKLflvR7kQqew=,tag:K4awQ5MMxUbnGQo8HYHOww==,type:str]
    SECRET_VAULTWARDEN_DB_ROOTPASS: ENC[AES256_GCM,data:XXUejLcjv6NRbglrq9RzPzVnE1Eirj8nyO65BvnK4pbd7Urg+6Q=,iv:mA2x+wzbctEp1xblN8E4hadCIFqiCTFh8li76Qyn7Cg=,tag:HheYTvPhZ7hpZMB0U3ievA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMUg5anpVR05DT2UvcCtv
            d2x5Y0lQMGRNK3ZMMFRsR0RWeUF3a0EzOVJnCkxURUYwanh2MzBIOWpkL2IwUFdi
            UHo2YXgvbk8zQ2ljTnNYV085K2F4UGsKLS0tIFZuVG5QOGhOYjJWY2lIY1lObHZm
            VmhjVU5VRTdWMXBZNkl1QTNTVkQwM1EKEm0yg+LAwlFLpx9FLE7vPQp3LVvtv8ZT
            FMb6jOje1ZmRPYARGMoj450PqxBAFQev3iGrhoTcDkeAOCyjoS6RvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-07T16:58:21Z"
    mac: ENC[AES256_GCM,data:5+p/WZaliPkhm+lUodBfjF4Kw29/TdQFXOyKvKoj3h31Xe0cvl8WsAY1NzZhHHEljTiP5mVr4SURmDZIcBzw50qh6T7Bu1Rdc1Y2H+fTEuh0kDuaHkDOXMJUQO0J4BXZDOClFkL2y9oFEnjRfQF33XOl7F/JTRbwxCUJE68IGKE=,iv:p4IeGdcqdomuS3TDjsYxAvo6vzL9MrvjAUNzK+K6oVE=,tag:HwwLWuu8duhjrMdWLnt7Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
