apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xWOJusep/nwLjQ==,iv:8cA/8exXqbNj3+lA1/aLfMgQ5rHPscbI/zyMgmeLJVE=,tag:XWNQ1oAJWAGlzIVQVogpRw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4vvW0etQH5c5fMydZb2LExlIG/8aZSR8xR64eMVcxA==,iv:Lwtra55nrh8kfks4aekkdHMOgDq1xO5wmagIgfv38uw=,tag:17LpkZ4y1CobJiv6XfzFnQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PUXKJWbac4IGn5eaTWxmakeVFOh/oauc2FMWuerkcj4IsRh7,iv:pbpV+8IMjWCPJ4rV1OzSTupqwNCGGF/bFeVkEdlDpRo=,tag:RYOjnnZPXuZrZCsfWDd4uw==,type:str]
    SECRET_MINIFLUX_POSTGRES_PASSWORD: ENC[AES256_GCM,data:RTcjTqPkctYzMg==,iv:1aPUxuAx1FMCRVGsCAwWg7Ngssx/8lgnR/ZocjhtGEM=,tag:iYvGhUlR4/quX0/x3Yg0+Q==,type:str]
    SECRET_EMAIL_SERVER: ENC[AES256_GCM,data:TkBGyrUWDuPl0nJoUSsVVcxn,iv:VrTHIQVz0/TOhoiaXkaV+8u3vDES+vKOu49dAETbyMw=,tag:jLplPmzQv7Iz+lR3e6ktuw==,type:str]
    SECRET_EMAIL_PORT: ENC[AES256_GCM,data:knSZc5w=,iv:eLMnWul7ojaPuv7IkBONcr0tFW4U3Pow9Ut1DIPO2qE=,tag:7Zad/JTVRIVZmV7oOeAzww==,type:str]
    SECRET_EMAIL_USERNAME: ENC[AES256_GCM,data:FLka3KgKrA4=,iv:OrEG8K9V/3Drcx752A0+6P03svIA6YUXLViU+iyjkvs=,tag:fy6gY8d7Dv3BPP8Uqc8Qyg==,type:str]
    SECRET_EMAIL_PASSWORD: ENC[AES256_GCM,data:s6WY3bYvnvo=,iv:8JJGM39qpTvG6rhO7pe9PbTNK/SkEZtKroYlZNGToX8=,tag:iDmsZ8rHBWWuOxwgxbaIZA==,type:str]
    SECRET_EMAIL_SECURITY: ENC[AES256_GCM,data:u1IUCtEgKfY=,iv:eBjHIKHJlF+vTyiREjOzskyQVGWRwZuDTXACtVJ7Bkk=,tag:OTF3KUWq/yPh2JxavXjfkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQm1mWk5yTTExMDJNOTBx
            dkNqNHRveEYvZ3F2TW1VUkdEeVB4MmRrc25nCnhUblQzTGZWUWNzSWtBY0c3d0l5
            RDl1RWltaVdvODVPdkk3ZkxjRWtNYXcKLS0tIDRTa1lpUDNkSHhOMmk5NjBVUW1Y
            aThPL3ZqejlnU1pkT1ZWcHhoTDVKY00Kc3T8Vk5QgvRW7TqjzFkCsGUiHRWZlEni
            AxOuHwaMcgcEIKhwHyM4FjiV6Upcf9/pKRPziz3oNLj/JSyve/2IbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T17:36:29Z"
    mac: ENC[AES256_GCM,data:HVy55HiQTzjxnLuXD9DhlKRvU6gxtZGtkhNI/6EUO3JhXPQwU7O/x49JjpKKvjqW/prYlZ8LaiC9tz9nbO1qXWbOkiHCySLVwn72iLiPKK2kJw0qcspb+Z+xvTMxSyKnjAjbIoYuL2C8kRsWIN0fvP5N09HvYByjabD2M1rLCIU=,iv:0s8ksu64gvJayVnCWYeEB/tsaUaIwiE75QUp9PteI38=,tag:VmSAEkUdq3dQRMsN5lbNXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
