apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fGTFtBq328o2yw==,iv:u6CmACgrBnX2c2tqLYMTETV012D2NJH+xgQYpl/eprs=,tag:0ojD/BimTH94dJAYgjl6BA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:jkSrrpisDaAq2K2NSOmONID+sfkBWNucUQ2T1uRYuA==,iv:RdGO33KSuWLrNba7Q1K8Px9lm9UnIuHBxBv4i8GR82k=,tag:TepDIbpsnzaeqZdj9v69qA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vm9ZFUrkBYDM2H8LBRxQyoYRNhyeOf7ikqu0mDlpHHdUFTco,iv:6JglCCMrlh2O5cim7mCc3DLfOGVN6LULpedNI5kzhXI=,tag:2kaT4rJltBgLq1aFFVhvfA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:8BErHZ7wzPMgec6I4Qb+qqK5plvNyVtkPir5zyzNensBKC3F7vdwu2lRDdK7SbqSmsd0bJbo2WyjfxF/t+tp6MGaKOCJ6YHOE5fl7Y3mGauFQjYclo3bM3RZ7OCNTMMY9VRySu2omAumWJuGqm2/oKOhftVDucop5mogioRO5wz+3mTMjd8=,iv:51PbAFj3v7Rk49nPQkiu5epzCbXKf8jfLdSImgA9gPU=,tag:d/YI7lC064Bu8eZSpq2v8g==,type:str]
    SECRET_VAULTWARDEN_DB_PASS: ENC[AES256_GCM,data:V2V4UrN6+tpS0deM6O+4Vm54xJhNI/hxZuK2playwU0UFBr4KZF8,iv:7xqC175AJn+S51bgemud71dVnhVrMyn5ZXK5p4jIN6U=,tag:rOd0zpXcGowyp58LcDY1VA==,type:str]
    SECRET_VAULTWARDEN_DB_ROOTPASS: ENC[AES256_GCM,data:j4f8fYZvJ3Tm+XlsYrw+oQcsSW89Ff5Oru6PFDkWi43ONbFkZdo=,iv:Ri/gkmRnjmzoUjOXUiiErSs+EsBdrsgLYAnb/iuFz5w=,tag:R23Oe5QWhVGUoAXvSN8Z3g==,type:str]
    SECRET_MINIFLUX_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Y4ukC0xzzKB59t7oKuYTHUOnbEk2ys9821If6ZaDR/1+,iv:3VDvHYLkFXxyR3oFXLD7ZEvP2QhPn9JJCzxEgNu919I=,tag:GHtuVu69zKcDHF/hTQLhSg==,type:str]
    SECRET_EMAIL_SERVER: ENC[AES256_GCM,data:t+oLiYPoJ9bou3hvnwj4O6hv,iv:Kg+qRa2WIvUdyazIr+F+TUUwaWljVApk/lCxzK2JPys=,tag:WEjJxlGH1HMZ8ZA5JvY9xg==,type:str]
    SECRET_EMAIL_PORT: ENC[AES256_GCM,data:u2FhUkM=,iv:JaZpAwZP/WQn/Att+iiD9wTP9+gB6D1ddA3Tew0SK/U=,tag:N36GotXZc3lFn3rKgz8LKA==,type:str]
    SECRET_EMAIL_USERNAME: ENC[AES256_GCM,data:LjICdbqhXyo=,iv:OmArdA6UDnH83v1F8zJJX84mQaKdg0KQV2N/oo43zEc=,tag:Z4TUlINWS+S3LQSm/rhuRQ==,type:str]
    SECRET_EMAIL_PASSWORD: ENC[AES256_GCM,data:XdQzO36H3Ic=,iv:QJuHcPHWfLWI8syRvghbljDb88gg03JA5NWpnwc/wqI=,tag:WUw7BBN4ht+8VC6pAMi8PA==,type:str]
    SECRET_EMAIL_SECURITY: ENC[AES256_GCM,data:Fl3guHHuYxM=,iv:4Nzh4trzTt57wHRTmUMTH4Ve/3tbLkWOO39n95BY3r0=,tag:ZYwFRBaJGxFJWzphhM8KZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s67ukj4fpgjny9j30hnpan4qmr4cn75sejsqrfv6yydgkte97gjscrc8p8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaTFabzM4RWVuUTJRUWor
            eWZDdUZIdVgwVVlFaVlEdE9zRTRxaythaWxZCm9wR1FzNTRJV3BKR0dwcGJqdzZj
            MURnL1VXd2U3MjFDRDZTZytGdDJMTXMKLS0tIDduYU41eXZmdGRIeURLMnkrWTVG
            Mjc4WmRpMU9ZY04vYkhpdFcraGJBeW8KQ6JmHxbxQNz6LWCWKG4o3hy3Qrl5QyPK
            TZ1pIrPeHKb/svjcXOSZgLjaMP+VuZdcsT+jE3XJp0kDs9QrjPFssw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-16T03:22:34Z"
    mac: ENC[AES256_GCM,data:xc3iZ1C1e+57Zil4wq9MSwyXKJCks2EhuIBjtv44Q8Uh9IeY/hMWXUr1KbCtfHJpw3sd5Af54r0MwtopFdFXyaAIZjqaZygzJwI9mne41rHzvOoBkJb9glzs39K1AN2u9QFLB/BdMavD5+sM72/SOaGwrHg+16X3SY8dQ8LfgPI=,iv:IrIoVuXrV0ndlP04Oy27OQPmwdf7ZtPJogPyAZbZB9E=,tag:JyVhzsuobJHnItFIwiIsnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
