---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: web
spec:
  interval: 10m0s
  chart:
    spec:
      chart: changedetection-io
      version: 0.8.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: gabe565-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/dgtlmoon/changedetection.io
      pullPolicy: IfNotPresent
      tag: 0.43@sha256:c2c05cc886ed3ad3f0dd53a199a7139a979daa85a95a30987eff3cc06176ce98
    env:
      TZ: America/Los_Angeles
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
        hosts:
          - host: &host "changedetection.${SECRET_DOMAIN}"
            paths:
              - path: /
    persistence:
      data:
        enabled: true
        mountPath: /datastore
        existingClaim: changedetection-data

    browserless:
      # -- Enable Browserless sidecar
      enabled: true
      image:
        # -- Browserless image repository
        repository: browserless/chrome
        # -- Browserless image tag
        tag: latest
        # -- Browserless image pull policy
        pullPolicy: Always
      # -- Browserless environment variables. [[ref]](https://docs.browserless.io/docs/docker.html)
      # @default -- See [values.yaml](./values.yaml)
      env:
        ENABLE_DEBUGGER: "false"
        DEFAULT_BLOCK_ADS: "true"
        DEFAULT_STEALTH: "true"
