---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data
  namespace: web
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G