---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-web-changedetection
  namespace: flux-system
spec:
  path: ./kubernetes/apps/web/changedetection/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: changedetection-io
      namespace: web
  interval: 30m
  retryInterval: 1m
  timeout: 3m
