---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secrets
  namespace: networking
type: Opaque
stringData:
  tunnel-config.json: >
    {
      "AccountTag": "${BOOTSTRAP_CLOUDFLARE_ACCOUNTTAG}",
      "TunnelSecret": "${BOOTSTRAP_CLOUDFLARE_TUNNELSECRET}",
      "TunnelID": "${BOOTSTRAP_CLOUDFLARE_TUNNELID}",
      "TunnelName": "${BOOTSTRAP_CLOUDFLARE_TUNNELNAME}"
    }