---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  SECRET_CLOUDFLARE_TUNNEL_ID: "${BOOTSTRAP_CLOUDFLARE_TUNNELID}"
  SECRET_MINIFLUX_POSTGRES_PASSWORD: "${BOOTSTRAP_SECRET_MINIFLUX_POSTGRES_PASSWORD}"
  SECRET_EMAIL_SERVER: "${BOOTSTRAP_SECRET_EMAIL_SERVER}"
  SECRET_EMAIL_PORT: "${BOOTSTRAP_SECRET_EMAIL_PORT}"
  SECRET_EMAIL_USERNAME: "${BOOTSTRAP_SECRET_EMAIL_USERNAME}"
  SECRET_EMAIL_PASSWORD: "${BOOTSTRAP_SECRET_EMAIL_PASSWORD}"
  SECRET_EMAIL_SECURITY: "${BOOTSTRAP_SECRET_EMAIL_SECURITY}"
