---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  SECRET_CLOUDFLARE_TUNNEL_ID: "${BOOTSTRAP_CLOUDFLARE_TUNNELID}"
  SECRET_VAULTWARDEN_ADMIN_TOKEN: "${BOOTSTRAP_SECRET_VAULTWARDEN_ADMIN_TOKEN}"
  SECRET_VAULTWARDEN_DB_PASS: "${BOOTSTRAP_SECRET_VAULTWARDEN_DB_PASS}"
  SECRET_VAULTWARDEN_DB_ROOTPASS: "${BOOTSTRAP_SECRET_VAULTWARDEN_DB_ROOTPASS}"