---
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-backups-secrets
    namespace: longhorn-system
stringData:
    AWS_ENDPOINTS: "${BOOTSTRAP_SECRET_B2_LONGHORN_BACKUPS_S3_URL}"
    AWS_ACCESS_KEY_ID: "${BOOTSTRAP_SECRET_B2_LONGHORN_BACKUPS_S3_ACCESSKEYID}"
    AWS_SECRET_ACCESS_KEY: "${BOOTSTRAP_SECRET_B2_LONGHORN_BACKUPS_S3_SECRETKEY}"
