---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./changedetection/kustomization.yaml
  - ./memos/kustomization.yaml
  - ./miniflux/kustomization.yaml
  - ./triliumnotes/kustomization.yaml